version: "3.7"
services:
 pgadmin:
       image: dpage/pgadmin4:6.4
       restart: always
       environment:
          PGADMIN_DEFAULT_EMAIL: test@test.com
          PGADMIN_DEFAULT_PASSWORD: test
          PGADMIN_LISTEN_PORT: 80
       ports:
          - "8080:80"
       volumes:
          - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
~
